---
# Copyright Red Hat
# SPDX-License-Identifier: Apache-2.0
# Author: Guillaume Abrioux <gabrioux@redhat.com>

- ansible.builtin.import_playbook: insecure-registries.yml
  when: set_insecure_registries | default(false) | bool

- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: import_role ceph_defaults
      import_role:
        name: ceph_defaults

    - name: fail when ceph_origin is custom with no repository defined
      fail:
        msg: "You must define 'ceph_custom_repositories' or 'custom_repo_url' when ceph_origin is 'custom'"
      when:
        - ceph_origin == 'custom'
        - custom_repo_url is undefined
        - ceph_custom_repositories is undefined